version: "3"
services:
  relaybroker:
    image: gempir/relaybroker:latest
    environment:
      LOGLEVEL: error
  
  gempbotgo:
    build: ./
    depends_on:
      - relaybroker
    ports:
      - "8025:8025"
    environment:
      IRCHOST: relaybroker:3333
    volumes:
      - /var/twitch_logs:/var/twitch_logs
      - ./configs:/configs
    