---
- name: update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install apt-transport-https
  apt: name=apt-transport-https state=present

- name: install htop
  apt: name=htop state=present

- name: install ufw firewall
  include: ufw.yml

- name: Ensure group "justlog" exists
  group:
    name: justlog
    state: present

- name: Create justlog user
  user:
    name: justlog
    shell: /bin/bash
    groups: justlog
    append: yes